# Generated by Django 4.2.9 on 2024-12-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='veg_nonveg',
            field=models.CharField(choices=[('veg', 'Vegetarian'), ('nonveg', 'Non-Vegetarian')], default='veg', max_length=6),
        ),
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.CharField(choices=[('Gravy', 'Gravy'), ('Side Dish', 'Side Dish'), ('Dosa', 'Dosa'), ('Rotis', 'Rotis'), ('Rice and Noodle', 'Rice and Noodle'), ('Dessert', 'Dessert'), ('Beverages', 'Beverages'), ('Snacks', 'Snacks'), ('Grill and Tandoori', 'Grill and Tandoori'), ('Soup', 'Soup'), ('Extras', 'Extras')], default='Extras', max_length=50),
        ),
    ]
