# Generated by Django 4.2.9 on 2024-12-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_dish_veg_nonveg_alter_dish_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50)),
                ('transaction_type', models.CharField(choices=[('online', 'Online'), ('cod', 'Cash on Delivery')], max_length=10)),
                ('order_name', models.CharField(max_length=200)),
                ('order_phonenumber', models.CharField(max_length=15)),
                ('agent_name', models.CharField(max_length=100)),
                ('order_status', models.CharField(choices=[('declined', 'Declined'), ('preparing', 'Preparing'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered')], max_length=20)),
                ('bill_value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Order Status',
                'verbose_name_plural': 'Order Statuses',
            },
        ),
        migrations.CreateModel(
            name='PlacedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50, unique=True)),
                ('transaction_type', models.CharField(choices=[('online', 'Online'), ('cod', 'Cash on Delivery')], max_length=10)),
                ('transaction_number', models.CharField(blank=True, max_length=100, null=True)),
                ('order_name', models.CharField(max_length=200)),
                ('order_phonenumber', models.CharField(max_length=15)),
                ('dish_name', models.CharField(max_length=255)),
                ('dish_quantity', models.PositiveIntegerField()),
                ('dish_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prep_status', models.CharField(default='pending', max_length=50)),
            ],
            options={
                'verbose_name': 'Placed Order',
                'verbose_name_plural': 'Placed Orders',
            },
        ),
    ]
