# Generated by Django 4.2.9 on 2024-12-25 14:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_orderstatus_placedorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstatus',
            options={},
        ),
        migrations.AlterModelOptions(
            name='placedorder',
            options={},
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='ordered_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='placedorder',
            name='ordered_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='agent_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='order_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='order_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='order_status',
            field=models.CharField(choices=[('declined', 'Declined'), ('preparing', 'Preparing'), ('out_for_delivery', 'Out for Delivery')], max_length=20),
        ),
        migrations.AlterField(
            model_name='placedorder',
            name='order_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='placedorder',
            name='order_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='placedorder',
            name='prep_status',
            field=models.CharField(max_length=50),
        ),
    ]
