# Generated by Django 4.2.9 on 2025-01-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_dish_tags_delete_orderstatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20, unique=True)),
                ('course_name', models.CharField(max_length=200)),
                ('regulation', models.PositiveIntegerField()),
                ('course_type', models.CharField(choices=[('core', 'Core'), ('elective', 'Elective'), ('open_elective', 'Open Elective'), ('honor', 'Honor'), ('minor', 'Minor'), ('add_on', 'Add On')], max_length=20)),
                ('lecture_points', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('tutorial_points', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('practical_points', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('credits', models.DecimalField(decimal_places=1, max_digits=3)),
                ('hours_per_week', models.PositiveIntegerField()),
                ('cia_marks', models.PositiveIntegerField()),
                ('see_marks', models.PositiveIntegerField()),
                ('total_marks', models.PositiveIntegerField(editable=False)),
                ('category', models.CharField(choices=[('theory', 'Theory'), ('practical', 'Practical'), ('both', 'Both')], max_length=20)),
                ('semester', models.PositiveIntegerField()),
                ('department', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('academic_year', models.CharField(max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['course_code'],
            },
        ),
    ]
