# Generated by Django 4.2.9 on 2025-01-27 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_course_options_alter_course_credits_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['course_code'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set(),
        ),
    ]
