# Generated by Django 4.2.9 on 2025-01-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_course_lecture_points_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('BE-BME', 'B.E. - BIOMEDICAL ENGINEERING'), ('BTECH-BT', 'B.Tech. - BIOTECHNOLOGY'), ('BE-EIE', 'B.E. - ELECTRONICS AND INSTRUMENTATION ENGINEERING'), ('BE-ECE', 'B.E. - ELECTRONICS AND COMMUNICATION ENGINEERING'), ('BE-EEE', 'B.E. - ELECTRICAL AND ELECTRONICS ENGINEERING'), ('BE-CSE', 'B.E. - COMPUTER SCIENCE AND ENGINEERING'), ('BE-CSD', 'B.E. - COMPUTER SCIENCE AND DESIGN'), ('BE-CIVIL', 'B.E. - CIVIL ENGINEERING'), ('BE-ISE', 'B.E. - INFORMATION SCIENCE AND ENGINEERING'), ('BE-MECH', 'B.E. - MECHANICAL ENGINEERING'), ('BE-MTE', 'B.E. - MECHATRONICS ENGINEERING'), ('BTECH-AE', 'B.Tech. - AGRICULTURAL ENGINEERING'), ('BTECH-AIDS', 'B.Tech. - ARTIFICIAL INTELLIGENCE AND DATA SCIENCE'), ('BTECH-AIML', 'B.Tech. - ARTIFICIAL INTELLIGENCE AND MACHINE LEARNING'), ('BTECH-CSBS', 'B.Tech. - COMPUTER SCIENCE AND BUSINESS SYSTEMS'), ('BTECH-CT', 'B.Tech. - COMPUTER TECHNOLOGY'), ('BTECH-FT', 'B.Tech. - FASHION TECHNOLOGY'), ('BTECH-FOOD', 'B.Tech. - FOOD TECHNOLOGY'), ('BTECH-IT', 'B.Tech. - INFORMATION TECHNOLOGY'), ('ME-CS', 'M.E. - COMMUNICATION SYSTEMS'), ('ME-CSE', 'M.E. - COMPUTER SCIENCE AND ENGINEERING'), ('ME-ISE', 'M.E. - INDUSTRIAL SAFETY ENGINEERING'), ('ME-SE', 'M.E. - STRUCTURAL ENGINEERING'), ('MBA', 'M.B.A. - MASTER OF BUSINESS ADMINISTRATION'), ('PHD-BT', 'Ph.D BIOTECHNOLOGY'), ('PHD-CHEM', 'Ph.D CHEMISTRY'), ('PHD-CIVIL', 'Ph.D CIVIL ENGINEERING'), ('PHD-CSE', 'Ph.D COMPUTER SCIENCE AND ENGINEERING'), ('PHD-EEE', 'Ph.D ELECTRICAL AND ELECTRONICS ENGINEERING'), ('PHD-ECE', 'Ph.D ELECTRONICS AND COMMUNICATION ENGINEERING'), ('PHD-EIE', 'Ph.D ELECTRONICS AND INSTRUMENTATION ENGINEERING'), ('PHD-IT', 'Ph.D INFORMATION TECHNOLOGY'), ('PHD-MATH', 'Ph.D MATHEMATICS'), ('PHD-MECH', 'Ph.D MECHANICAL ENGINEERING'), ('PHD-MTE', 'Ph.D MECHATRONICS'), ('PHD-PHY', 'Ph.D PHYSICS'), ('PHD-MGT', 'Ph.D SCHOOL OF MANAGEMENT STUDIES')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='year_of_study',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'First Year'), (2, 'Second Year'), (3, 'Third Year'), (4, 'Fourth Year')], null=True),
        ),
    ]
