# Generated by Django 4.2.9 on 2025-01-27 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_course_course_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('BE-BME', 'B.E. - BIOMEDICAL ENGINEERING'), ('BTECH-BT', 'B.Tech. - BIOTECHNOLOGY'), ('BE-EIE', 'B.E. - ELECTRONICS AND INSTRUMENTATION ENGINEERING'), ('BE-ECE', 'B.E. - ELECTRONICS AND COMMUNICATION ENGINEERING'), ('BE-EEE', 'B.E. - ELECTRICAL AND ELECTRONICS ENGINEERING'), ('BE-CSE', 'B.E. - COMPUTER SCIENCE AND ENGINEERING'), ('BE-CSD', 'B.E. - COMPUTER SCIENCE AND DESIGN'), ('BE-CIVIL', 'B.E. - CIVIL ENGINEERING'), ('BE-ISE', 'B.E. - INFORMATION SCIENCE AND ENGINEERING'), ('BE-MECH', 'B.E. - MECHANICAL ENGINEERING'), ('BE-MTE', 'B.E. - MECHATRONICS ENGINEERING'), ('BTECH-AE', 'B.Tech. - AGRICULTURAL ENGINEERING'), ('BTECH-AIDS', 'B.Tech. - ARTIFICIAL INTELLIGENCE AND DATA SCIENCE'), ('BTECH-AIML', 'B.Tech. - ARTIFICIAL INTELLIGENCE AND MACHINE LEARNING'), ('BTECH-CSBS', 'B.Tech. - COMPUTER SCIENCE AND BUSINESS SYSTEMS'), ('BTECH-CT', 'B.Tech. - COMPUTER TECHNOLOGY'), ('BTECH-FT', 'B.Tech. - FASHION TECHNOLOGY'), ('BTECH-FOOD', 'B.Tech. - FOOD TECHNOLOGY'), ('BTECH-IT', 'B.Tech. - INFORMATION TECHNOLOGY'), ('ME-CS', 'M.E. - COMMUNICATION SYSTEMS'), ('ME-CSE', 'M.E. - COMPUTER SCIENCE AND ENGINEERING'), ('ME-ISE', 'M.E. - INDUSTRIAL SAFETY ENGINEERING'), ('ME-SE', 'M.E. - STRUCTURAL ENGINEERING'), ('MBA', 'M.B.A. - MASTER OF BUSINESS ADMINISTRATION'), ('PHD-BT', 'Ph.D BIOTECHNOLOGY'), ('PHD-CHEM', 'Ph.D CHEMISTRY'), ('PHD-CIVIL', 'Ph.D CIVIL ENGINEERING'), ('PHD-CSE', 'Ph.D COMPUTER SCIENCE AND ENGINEERING'), ('PHD-EEE', 'Ph.D ELECTRICAL AND ELECTRONICS ENGINEERING'), ('PHD-ECE', 'Ph.D ELECTRONICS AND COMMUNICATION ENGINEERING'), ('PHD-EIE', 'Ph.D ELECTRONICS AND INSTRUMENTATION ENGINEERING'), ('PHD-IT', 'Ph.D INFORMATION TECHNOLOGY'), ('PHD-MATH', 'Ph.D MATHEMATICS'), ('PHD-MECH', 'Ph.D MECHANICAL ENGINEERING'), ('PHD-MTE', 'Ph.D MECHATRONICS'), ('PHD-PHY', 'Ph.D PHYSICS'), ('PHD-MGT', 'Ph.D SCHOOL OF MANAGEMENT STUDIES')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoreSubjectRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6'), (7, 'Semester 7'), (8, 'Semester 8')])),
                ('year', models.IntegerField(choices=[(1, 'First Year'), (2, 'Second Year'), (3, 'Third Year'), (4, 'Fourth Year')])),
                ('regulation', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courses', models.ManyToManyField(related_name='core_rules', to='home.course')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_rules', to='home.program')),
            ],
            options={
                'ordering': ['program', 'semester'],
                'unique_together': {('program', 'semester', 'regulation')},
            },
        ),
    ]
