# Generated by Django 4.2.9 on 2025-01-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_userprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderstatus',
            old_name='order_name',
            new_name='dish_name',
        ),
        migrations.RenameField(
            model_name='orderstatus',
            old_name='order_phonenumber',
            new_name='recipient_phonenumber',
        ),
        migrations.RenameField(
            model_name='placedorder',
            old_name='order_name',
            new_name='recipient_name',
        ),
        migrations.RenameField(
            model_name='placedorder',
            old_name='order_phonenumber',
            new_name='recipient_phonenumber',
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='delivery_type',
            field=models.CharField(choices=[('dinein', 'Dine-In'), ('parcel', 'Parcel')], default='parcel', max_length=10),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='dish_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='dish_quantity',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='recipient_name',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='transaction_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='placedorder',
            name='delivery_type',
            field=models.CharField(choices=[('dinein', 'Dine-In'), ('parcel', 'Parcel')], default='dinein', max_length=10),
        ),
        migrations.AlterField(
            model_name='placedorder',
            name='dish_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='placedorder',
            name='prep_status',
            field=models.BooleanField(default=False),
        ),
    ]
