# Generated by Django 4.2.9 on 2025-01-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_course_options_alter_course_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
