# Generated by Django 4.2.9 on 2025-01-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_course_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='lecture_points',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='L'),
        ),
        migrations.AlterField(
            model_name='course',
            name='practical_points',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='P'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tutorial_points',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='T'),
        ),
    ]
